# CodeRabbit Configuration
# Reference: https://docs.coderabbit.ai/reference/configuration
# Last updated: 2025-10-20

language: en-US
early_access: true

reviews:
  profile: chill
  review_status: false  # Stop posting "Review skipped" status comments
  poem: false
  in_progress_fortune: false
  collapse_walkthrough: true
  auto_title_instructions: "Conventional commit style"

  auto_review:
    enabled: true
    drafts: false
    labels:
      - "!wip"  # Don't review PRs with 'wip' label
    base_branches:
      - "main"
      - "fix/.*"
      - "feat/.*"
      - "chore/.*"
      - "docs/.*"
      - "gt/.*"      # Graphite stacked branches with slash prefix
      - "gt-.*"      # Graphite stacked branches with dash prefix
      - "mono-.*"    # Linear-generated branches for MONO team
      - "id-.*"      # Linear-generated branches for ID team
      - ".*-mono-[0-9]+"  # Linear-generated branches like feature-mono-123
      - ".*-id-[0-9]+"    # Linear-generated branches like feature-id-123

  tools:
    biome:
      enabled: true
    gitleaks:
      enabled: true

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "/**/AGENTS.md"
      - "/**/CLAUDE.md"
      - "/.agent/**/*.md"
      - "/.claude/**/*.md"
      - "/.agents/rules/**/*.md"
      - "/packages/*/CLAUDE.md"
      - "/shared/*/CLAUDE.md"

  linear:
    usage: enabled
    team_keys:
      - "MONO"  # Outfitter Monorepo team
      - "ID"    # Outfitter team
      - "BLZ"   # Blaze team
      - "RGR"   # Ranger team
      - "RULE"  # Ruleset team
      - "WAY"   # Waymarks team
      - "CB"    # Codebase team
      - "CLI"   # CLI team

chat:
  integrations:
    linear:
      usage: enabled
