/**
 * Projects the authored token object (src/tokens.ts) into a flat set of CSS
 * custom properties under `:root`. One write (the TS object), one read here —
 * the CSS file is generated and checked in so consumers need no build step.
 */
import { tokens } from "../src/tokens";

const lines: string[] = [
  "/* Generated by scripts/build-css.ts — do not edit by hand. */",
  ":root {",
];

for (const [group, entries] of Object.entries(tokens)) {
  for (const [key, value] of Object.entries(
    entries as Record<string, string>
  )) {
    lines.push(`  --ot-${group}-${key}: ${value};`);
  }
}

lines.push("}");

const out = new URL("../tokens.css", import.meta.url);
await Bun.write(out, `${lines.join("\n")}\n`);
console.log(`Generated ${out.pathname}`);
